/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_appsync_graphqlEndpoint": "https://64ogn6qvqrfcfnbqew4yact3b4.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qj4jlfn6dvgexjr5mvqi7fy4ei",
    "aws_cognito_identity_pool_id": "eu-north-1:79e5bcd4-fffe-4bec-be5b-ea9364f10add",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_tEexDeDHw",
    "aws_user_pools_web_client_id": "7vbf00jkd3rtlhclf0urbo2eph",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
